### ISSUE TITLE
Road_Trip

### ISSUE THREAD

**Issue by BryanAbuchery** [chifwete/LINUX-TRAINING#1]
**Let us plan for a road trip**
These are the items that we will need;

- [x] Money
- [x] More money
- [x] More and more money

**Comment by chifwete** [comment]
List of things we need to carry.
Please include

**Comment by fredrickkebaso** [comment]
Places we need to visit:
    1.escarpements
    2.

**Comment by BryanAbuchery** [comment]
Thank you guys for contributing
